export const nameDirectory = new Map()
nameDirectory.set('albon', 'Alex Albon')
nameDirectory.set('leclerc', 'Charles Leclerc')
nameDirectory.set('ocon', 'Esteban Ocon')
nameDirectory.set('alonso', 'Fernando Alonso')
nameDirectory.set('russel', 'George Russell')
nameDirectory.set('zhou', 'Zhou Guanyu')
nameDirectory.set('magnussen', 'Kevin Magnussen')
nameDirectory.set('stroll', 'Lance Stroll')
nameDirectory.set('norris', 'Lando Norris')
nameDirectory.set('hamilton', 'Lewis Hamilton')
nameDirectory.set('sargeant', 'Logan Sargeant')
nameDirectory.set('verstappen', 'Max Verstappen')
nameDirectory.set('hulkenberg', 'Nico Hülkenberg')
nameDirectory.set('ricardo', 'Daniel Ricciardo')
nameDirectory.set('piastri', 'Oscar Piastri')
nameDirectory.set('gasly', 'Pierre Gasly')
nameDirectory.set('sainz', 'Carlos Sainz')
nameDirectory.set('perez', 'Sergio Pérez')
nameDirectory.set('bottas', 'Valtteri Bottas')
nameDirectory.set('tsunoda', 'Yuki Tsunoda')
nameDirectory.set('Sauber', 'Kick Sauber')
nameDirectory.set('RB', 'RB Visa')
nameDirectory.set('Alpine', 'Alpine')
nameDirectory.set('Aston Martin', 'Aston Martin')
nameDirectory.set('Ferrari', 'Ferrari')
nameDirectory.set('Haas', 'Haas')
nameDirectory.set('McLaren', 'McLaren')
nameDirectory.set('Mercedes', 'Mercedes')
nameDirectory.set('Red Bull', 'Red Bull')
nameDirectory.set('Williams', 'Williams')

export const driverIds = ['albon', 'leclerc','ocon', 'alonso', 'russel', 'zhou', 'magnussen', 'stroll', 'norris', 'hamilton', 'sargeant', 'verstappen', 'hulkenberg',
    'ricardo', 'piastri', 'gasly', 'sainz', 'perez', 'bottas', 'tsunoda']

export const constructorIds =['Sauber', 'RB', 'Alpine', 'Aston Martin', 'Ferrari', 'Haas', 'McLaren', 'Mercedes', 'Red Bull', 'Williams']